name: flutter_wishlist_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.13
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  local_auth: ^1.1.11
  riverpod: ^1.0.3
  shared_preferences: ^2.0.13
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/1024.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300